version: '3.8'

services:
  gateway:
    container_name: shareit-gateway
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - SERVER_PORT=8080

  server:
    container_name: shareit-server
    build: ./server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - WEB_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=qwerty
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

  db:
    container_name: shareit-db
    image: postgres:16.3-alpine
    volumes:
      - vol:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=qwerty

volumes:
  vol:
